### ISSUE TITLE
vscode的dark+主题感觉更好看

### ISSUE THREAD

**Issue by SkyRunner123** [UranusSong/VS-style-theme-for-clion#1]
楼主能出一个这样的主题吗
![image](https://user-images.githubusercontent.com/62864933/117005113-709c2100-ad19-11eb-9dd9-1eec5f7b36e8.png)

**Comment by marrblue** [comment]
@SkyRunner123 确实，不过clion中的高亮体系和vscode稍微有点不一样，做到完全相同很难。现在我也很少用clion了，大多会直接用vscode。如果你有时间，非常欢迎你PR一个这种主题 ：)
